### ISSUE TITLE
Make sure the ArrayList isn't empty before trying to check location 0

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#36]
https://github.com/JustBru00/RenamePlugin/blob/282406dd0f0383655d0f6a11be4c139f930e1771/src/com/gmail/justbru00/epic/rename/main/RenameRewrite.java#L166

Example Error:
`14.09 08:23:35 [Server] ERROR null 14.09 08:23:35 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'lore' in plugin EpicRename v2.6.1 14.09 08:23:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:672) ~[patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91] 14.09 08:23:35 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91] 14.09 08:23:35 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 14.09 08:23:35 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_91] 14.09 08:23:35 [Server] INFO at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_91] 14.09 08:23:35 [Server] INFO at com.gmail.justbru00.epic.rename.main.RenameRewrite.checkMaterialBlacklist(RenameRewrite.java:176) ~[?:?] 14.09 08:23:35 [Server] INFO at com.gmail.justbru00.epic.rename.commands.Lore.onCommand(Lore.java:93) ~[?:?] 14.09 08:23:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.10.2.jar:git-Paper-845] 14.09 08:23:35 [Server] INFO ... 15 more 14.09 08:23:39 [Server] INFO [Obsidian] The_Rolly_Knight: it says: an internetional error occurred while attemping to perform this command`

Example Config:
http://pastebin.com/vM99wKpV

**Comment by JustBru00** [comment]
Closed in Release version 2.6.2
