### ISSUE TITLE
Material blacklist only works for the first material

### ISSUE THREAD

**Issue by despawningbone** [JustBru00/RenamePlugin#38]
For some reason in the material blacklist it only blacklists the first material (tripwire hook) but not the second one(spawner):

```
# EpicRename Configuration File
# This is Color Code compatible (&)

# To opt out of sending anonymous stats to mcstats.org change this to true.
opt-out: 'true'

# Prefix for all messages
prefix: '&f[&b&lSky&r&2cube&r] ' 

# Economy Settings
economy:
   use: true
   costs:
      rename: 500      
      lore: 2000
      renameentity: 5000
      
# Don't change this!
Config Version: 5

# When a player doesn't have permission.
no permission: '&cYou do not have the permission to use this command!'

# When player puts too many or too little args. example: if a player types (/rename test good) or (/rename) without putting a name.
not enough or too many args: '&cIncorrect argument format! Do /rhelp for more info.'

# When a player tries to rename air. (Not a good idea :D)
item in hand is air: '&cYou are not currently holding any item.'

#For /rename only.
you do not have permission for that item: '&cYou do not have the correct permission for that material.'

# What prints to console when item is renamed in /rename. example: playername (automatic) + your msg (below) + the renamed item name (automatic)
your msg: ' &arenamed an item to&r '

#What gets sent to the player when a item is renamed.
rename complete: '&aItem renamed.'

#What gets said if player doesn't give at least one word after /lore
lore usage: '&cPlease put at least one word after /lore'

# What gets said when a item is /lore successfully
lore complete: '&aItem relored'

#Character Limit (Bypass with "epicrename.bypass.charlimit")
charlimit: 30
charlimitenabled: true
charlimitmessage: '&cSorry, the message you typed is too long &7(&e>{char}&7). Please shorten the message and try again.'
charlimitbypassmessage: '&aYou just bypassed the character limit.'

#Blacklist Section

# List of valid bukkit materials that can't be renamed.
material blacklist:
 - TRIPWIRE_HOOK
 - MOB_SPAWNER

#If the plugin finds a blacklisted word.
found blacklisted word: '&4That message contains a blacklisted word that is forbidden to use. Please remove it.'

#If the plugin finds a blacklisted word.
found blacklisted material: '&4Sorry, but that material cannot be renamed.'

#If any of these words are found the plugin will stop the rename and print the message above.
blacklist:
 - anal
 - 
 - 
```
The above is my config.yml. there are no errors in the console. Am i doing it wrong or something?

Please help!
------------------------------------------------------------------------------------------------------------------
Server running git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins (37): CoreProtect, TTA, BlockParticles, WorldEdit, CrazyCrates, AnimatedScoreboard, CustomPermissionMessages, Essentials, iChatPlus, PlaceholderAPI, DisableJoinMessage, PlugMan, HolographicDisplays, VoidSpawn, WorldGuard, Friends2_0, AutoRestart, EssentialsProtect, EssentialsChat, Duels, EssentialsAntiBuild, PermissionsEx, NoEscape, hub, mcMMO, Vault, EssentialsSpawn, MyCommand, OreGeneratorRevolution, WithdrawAdvanced, SignShop, SilkSpawners, ChatFormat, ASkyBlock, CrazyAuctions, BossShop, EpicRename

**Comment by JustBru00** [comment]
What version of EpicRename are you using?

**Comment by despawningbone** [comment]
2.6.2

**Comment by JustBru00** [comment]
Are you op? Do you have * permissions or have the permisision `epicrename.bypass.materialblacklist`?

**Comment by despawningbone** [comment]
i deoped myself before this test

**Comment by JustBru00** [comment]
Try giving your self `-epicrename.bypass.materialblacklist` permission and see if that works.

**Comment by despawningbone** [comment]
it worked! thx for the help.
but i do not have that permission added on myself(and the perm groups), so will it be a bug?

**Comment by despawningbone** [comment]
and by the way if i include double "&" signs in the blacklist like this:
e.g:
blacklist:
 - anal
 - &b&lKey
 - 
it will output this error:

```
[22:35:05] [Server thread/ERROR]: Cannot load plugins\EpicRename\config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning an anchor
 in 'string', line 68, column 4:
     - &b&lKey
       ^
expected alphabetic or numeric character, but found &(38)
 in 'string', line 68, column 6:
     - &b&lKey
         ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:188) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at com.gmail.justbru00.epic.rename.main.RenameRewrite.<init>(RenameRewrite.java:62) [EpicRename%20v2.6.2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_102]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_102]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_102]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_102]
	at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_102]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:275) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:238) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:299) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning an anchor
 in 'string', line 68, column 4:
     - &b&lKey
       ^
expected alphabetic or numeric character, but found &(38)
 in 'string', line 68, column 6:
     - &b&lKey
         ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1446) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAnchor(ScannerImpl.java:939) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:370) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:504) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 28 more
```

**Comment by JustBru00** [comment]
I think you need to place '' around the words.

```#If any of these words are found the plugin will stop the rename and print the message above.
blacklist:
 - 'anal'
 - '&b&lKey'
 - ```

**Comment by despawningbone** [comment]
that worked too! thx so much for the help :)

**Comment by JustBru00** [comment]
No problem.
