### ISSUE TITLE
/Rename is no longer working for some reason

### ISSUE THREAD

**Issue by despawningbone** [JustBru00/RenamePlugin#39]
Sorry to interrupt you again but this time i got this error:

```
[21:03:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rename' in plugin EpicRename v2.6.2
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_102]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_102]
    at com.gmail.justbru00.epic.rename.main.RenameRewrite.checkMaterialBlacklist(RenameRewrite.java:191) ~[?:?]
    at com.gmail.justbru00.epic.rename.commands.Rename.onCommand(Rename.java:65) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    ... 15 more
```

This error will occur everytime when i use /rename in the correct way (eg typing /rename &4test(not incorrect format like plain /rename)) and it wont rename the item.
I suspect this is due to the material blacklist messing up as:
- In the error: 
  
  > com.gmail.justbru00.epic.rename.main.RenameRewrite.checkMaterialBlacklist(RenameRewrite.java:191) ~[?:?]
- if i have epicrename.bypass.materialblacklist i can use the plugin normally.

Here is my config.yml:

```
# EpicRename Configuration File
# This is Color Code compatible (&)

# To opt out of sending anonymous stats to mcstats.org change this to true.
opt-out: 'true'

# Prefix for all messages
prefix: '&f[&b&lSky&r&2cube&r] ' 

# Economy Settings
economy:
   use: true
   costs:
      rename: 500      
      lore: 2000
      renameentity: 5000

# Don't change this!
Config Version: 5

# When a player doesn't have permission.
no permission: '&cYou do not have the permission to use this command!'

# When player puts too many or too little args. example: if a player types (/rename test good) or (/rename) without putting a name.
not enough or too many args: '&cIncorrect argument format! Do /rhelp for more info.'

# When a player tries to rename air. (Not a good idea :D)
item in hand is air: '&cYou are not currently holding any item.'

#For /rename only.
you do not have permission for that item: '&cYou do not have the correct permission for that material.'

# What prints to console when item is renamed in /rename. example: playername (automatic) + your msg (below) + the renamed item name (automatic)
your msg: ' &arenamed an item to&r '

#What gets sent to the player when a item is renamed.
rename complete: '&aItem renamed.'

#What gets said if player doesn't give at least one word after /lore
lore usage: '&cPlease put at least one word after /lore'

# What gets said when a item is /lore successfully
lore complete: '&aItem relored.'

#Character Limit (Bypass with "epicrename.bypass.charlimit")
charlimit: 30
charlimitenabled: true
charlimitmessage: '&cSorry, the message you typed is too long &7(&e>{char}&7). Please shorten the message and try again.'
charlimitbypassmessage: '&aYou just bypassed the character limit.'

#Blacklist Section

# List of valid bukkit materials that can't be renamed.
material blacklist:
 - TRIPWIRE_HOOK
 - MOB_SPAWNER
 - 

#If the plugin finds a blacklisted word.
found blacklisted word: '&4That message contains a blacklisted word that is forbidden to use. Please remove it.'

#If the plugin finds a blacklisted word.
found blacklisted material: '&4Sorry, but that material cannot be renamed.'

#If any of these words are found the plugin will stop the rename and print the message above.
blacklist:
 - anal
 - '&2Cube&b&lKey'
 - '&bVote_&6Key'
```

have i done something wrong for the config file?
## Please help!

Server running git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins (37): CoreProtect, TTA, BlockParticles, WorldEdit, CrazyCrates, AnimatedScoreboard, CustomPermissionMessages, Essentials, iChatPlus, PlaceholderAPI, DisableJoinMessage, PlugMan, HolographicDisplays, VoidSpawn, WorldGuard, Friends2_0, AutoRestart, EssentialsProtect, EssentialsChat, Duels, EssentialsAntiBuild, PermissionsEx, NoEscape, hub, mcMMO, Vault, EssentialsSpawn, MyCommand, OreGeneratorRevolution, WithdrawAdvanced, SignShop, SilkSpawners, ChatFormat, ASkyBlock, CrazyAuctions, BossShop, EpicRename

**Comment by despawningbone** [comment]
Also, from this error i found a minor "bug": the plugin doesnt update the player's permission(at least for epicrename.bypass.materialblacklist) until he left and rejoin. Maybe look into that too(I might be wrong tho)?

**Comment by JustBru00** [comment]
Permissions should update instantly. Maybe your permissions plugin does something? Anyway try making your material blacklist look like this: https://gist.github.com/JustBru00/4ee51bba7ca8505a96a06bfeb8856cd1

That might fix it.

**Comment by JustBru00** [comment]
Also thanks for giving so much information at once. It really helps to have ALL of the information right away.

**Comment by despawningbone** [comment]
I still have the error even if i used your format :/

**Comment by despawningbone** [comment]
Also one side note: it was working perfectly when i fixed the older issue i posted here. some hours later when i joined the server again there is this issue. I tried to restart the server, reinstall the plugin, they just doesn't work.

**Comment by despawningbone** [comment]
It definitely is an error of the config.yml as i just used the default one and its fine. I am going to try to reformat the config to see if it will work.

**Comment by JustBru00** [comment]
Okay tell me how it goes. You should be able to see if a YML file is valid here: http://codebeautify.org/yaml-validator

**Comment by despawningbone** [comment]
I foud out when there's a valid material in the material blacklist it will have this error, otherwise it is totally fine. Also, just validated my config.yml, its totally fine.

**Comment by JustBru00** [comment]
I will try and help you more as soon as possible, but my pc seems to have a virus so I am trying to get that fixed.

**Comment by JustBru00** [comment]
I am going to try and reproduce this soon. I will tell you when I find a fix.

**Comment by despawningbone** [comment]
sure! thx for the help!

**Comment by JustBru00** [comment]
I am working on updating the entire plugin. This should fix the problem you are having. I will tell you when it is ready for release.

**Comment by JustBru00** [comment]
Please try the new release of EpicRename v3.0.
