### ISSUE TITLE
ERROR: AIR passed to the Blacklists.checkExistingName() check causes a null pointer exception

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#85]
```[16:33:32 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lore' in plugin EpicRename v3.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at com.gmail.justbru00.epic.rename.utils.v3.Blacklists.checkExistingName(Blacklists.java:31) ~[?:?]
        at com.gmail.justbru00.epic.rename.utils.v3.LoreUtil.loreHandle(LoreUtil.java:163) ~[?:?]
        at com.gmail.justbru00.epic.rename.commands.v3.Lore.onCommand(Lore.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        ... 15 more
[16:33:43 INFO]: JustBru00 issued server command: /lore &c&lClick to UNLOCK for 5600|&7Your best time: &eNever Finished|&7Times Finished: &e0|&7Attempts: &e0
[16:33:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lore' in plugin EpicRename v3.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at com.gmail.justbru00.epic.rename.utils.v3.Blacklists.checkExistingName(Blacklists.java:31) ~[?:?]
        at com.gmail.justbru00.epic.rename.utils.v3.LoreUtil.loreHandle(LoreUtil.java:163) ~[?:?]
        at com.gmail.justbru00.epic.rename.commands.v3.Lore.onCommand(Lore.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-4a03053]
        ... 15 more```

**Comment by JustBru00** [comment]
Appears to be caused by AIR in the Blacklists.chestExistingName() check
